apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
status: {}
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: infra
    repoURL: "https://github.com/insuusvenerati/argo-bootstrap"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
