apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagger
  namespace: argocd
status: {}
spec:
  destination:
    namespace: linkerd
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: flagger
    helm:
      parameters:
        - name: ingressClass
          value: nginx
        - name: meshProvider
          value: linkerd
        - name: metricsServer
          value: "http://prometheus.linkerd-viz:9090"
      valueFiles:
        - values.yaml
    repoURL: "https://flagger.app"
    targetRevision: 1.13.0
  syncPolicy:
    automated: {}
